//COMANDO PARA IMPRIMIR AS INFORMÇÕES NA TELA//
console.log("Hello World");

/* 
    ESTE MÉTODO DE COMENTÁRIO PERMITE
    A QUEBRA EM MÚLTIPLAS LINHAS DO 
    QUE SE PRETENDE DOCUMENTAR EM SEUS
    TRECHOS DE CÓDIGO.
*/