//USANDO VARIÁVEL LET
let num = 1;
{
    let num = 2;
    console.log("DENTRO DO ESCOPO =", num);
}

console.log("FORA DO ESCOPO =", num);

/*
 * ENQUANTO A VARIÁVEL DO TIPO VAR FICA DENTRO DO ESCOPO GLOBAL DO CÓDIGO,
 * SALVO OS CASOS DECLARADOS DENTRO DE FUNÇÕES,
 * AS VARIÁVEIS DO TIPO LET SÃO MAIS RIGOROSAS QUANTO A DECLARAÇÃO DAS MESMAS,
 * SENDO ELAS VISÍVEIS APENAS DENTRO DO ESCOPO ONDE ELAS FORAM DECLARADAS.
 */

console.log(" ");

/**
 * IMPORTANTE TAMBÉM!!
 * AS VARÁVEIS DO TIPO LET TAMBÉM SÃO VISTAS NO ESCOPO GLOBAL DO PROGRAMA, CONTUDO
 * DENTRO DO BLOCO EM EXECUÇÃO ELE DARÁ PRIORIDADE AS VARIÁVEIS CONTIDAS LÁ,
 * POR EXEMPLO...
 * CASO EXISTA UMA CHAMADA PARA UMA VARIÁVEL NÃO DECLARADA DENTRO DAQUELE ESCOPO
 * O PROGRAMA IRÁ BUSCAR NO ESCOPO GLOBAL, COMO DESCRITO ABAIXO...
 */

 let num1 = 1;
 {
     let num2 = 2;
     console.log("DENTRO DO ESCOPO =", num1);
 }
 
 console.log("FORA DO ESCOPO =", num1);